DEFS_PLATFORM = -DCONFIG_OPPO_FINGERPRINT_PLATFORM=6768
ccflags-y += -I$(srctree)/drivers/misc/mediatek/masp/asfv2/asf_inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/masp/asfv2/asf_export_inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/masp/asfv2/module

ccflags-y += $(DEFS_PLATFORM)

obj-y     +=  oppo_fp_common.o

