obj-$(CONFIG_OPPO_COMMON_SOFT)  +=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)  +=  oppo_devinfo/
obj-y += oppo_custom/
obj-$(CONFIG_OPPO_CRITICALLOG)  +=  oppo_criticallog/

#ifdef VENDOR_EDIT
#* Bin.Xu@BSP.Kernel.Stability, 2019/12/2, Add for oppo force dump */
obj-$(CONFIG_OPPO_FORCE_DUMP)     +=  oppo_dump/
#endif /* VENDOR_EDIT */
