# SPDX-License-Identifier: GPL-2.0
#ifdef VENDOR_EDIT
#Ping.Liu@BSP.Fingerprint.Secure, 2020/05/18, add for open trustonic tee, config tee.
#endif /*VENDOR_EDIT*/
obj-$(CONFIG_TEE) += tee.o
tee-objs += tee_core.o
tee-objs += tee_shm.o
tee-objs += tee_shm_pool.o
obj-$(CONFIG_OPTEE) += optee/
